Use latest sphinx version to build cache key
DataDog/datadog-api-client-python pull request #1299
Opened 2023-01-11 20:21 UTC by skarimo

SSIA

2023-01-13 19:53 UTC, nkzou approved these changes

2023-01-16 16:12 UTC, therve requested changes

2023-01-16 16:12 UTC, therve commented on .github/workflows/docs.yml
> +            awk -F ", " '{print $NF}')" >> $GITHUB_ENV
I'd do something like that instead:

```
tox -edocs --notest
SPHINX_VERSION=$(.tox/docs/bin/python -c "import importlib.metadata;print(importlib.metadata.version('sphinx'))")

````

2023-01-17 18:04 UTC, therve approved these changes

2023-01-17 18:32 UTC, merged